### ISSUE TITLE
Initial UI/UX thoughts

### ISSUE THREAD

**Issue by kirkbushell** [Yord/warfaster#1] opened 2022-10-04 03:31 UTC
Hey man! Firstly, thanks for inviting me to take a look - it's pretty clear to see you've done a metric fuckton of work to get this to where it is, so I thought I'd start by first raising some UI/UX concerns that I think should be highest priority beyond feature development. Many of these you're probably already across, and I could probably throw my weight into the UX corner to resolve many of these for you :)

1. Load times are crazy slow the first time you load. I don't know if this is a React issue, a configuration or environment issue, or something else. But it took about 20-30 seconds for all the data to load initially. Subsequent refreshes were snappy. I just saw it's requesting data from the wiki... now I see the problem. hahaha. I think that has to change. There isn't that much data, could easily have it sit in a JSON document and go about it that way.
2. List building is a bit... confusing? I'm not sure how to start/save lists.etc. I can add units and whatnot, with no validation.etc (Ie. I can add anything), but then I don't know how to remove or start a new list.
3. Spacing around the app is a bit inconsistent, and this could be cleaned up. Also just a few tweaks I would make to loading.etc. to communicate and cleanup the UI, such as moving the loading indicator when clicking on a unit to the right of the box, and then expand when ready (does that make sense?), rather than expanding initially with a loading indicator and then full expand when done. I also think the unit info could be broken down into several "tabs", with first tab being stats, abilities.etc. Advantages I think should be the icons, but I can tap them to show a tooltip with the full ruling. This will save a lot of space.
4. Okay, just figured out adding new lists. Yeah this is a confusing bit of UI. I would expect to see a list of erm... lists? hehe, and then the ability to add new ones, select faction, and then have units and cyphers automatically filtered based on that selection. 

I think that'll do for now :)

I just wanna say a few other things so you don't think/feel I'm just giving you shit. I think the UI is SUPER cool. Like, it really fits the universe and from just an overall aesthetic and "feel", I think you've nailed it. It looks awesome :)

I think with a bit of time on tweaking, particularly around performance and UX, you'll have a fantastic app on your hands and I'd be surprised if PP doesn't support you on it. If you/we can do a great job on it, they may feel they don't need to build one, and that is imho, the absolute ideal position to be in.

Finally, if you want code contributions, happy to help :)

**Comment by Yord** [comment] 2022-10-04 20:38
Hey thank you so much for your time and effort, very much appreciated :)! Unfortunately, I was not able to spend enough time to do it justice, yet. But I wanted to at least write a quick response to show my gratitude. Hope to have more time tomorrow.

**Comment by Yord** [comment] 2022-10-09 10:29
@kirkbushell Ok, coming back to your feedback :).

1.  Yeah load times are crazy on startup. The reason is, as you already stated, the page is being synchronized with the wiki content. While crawling the wiki, I am extra polite at the moment, only crawling a single page every 2 seconds, which adds up to the 30 seconds you observed. I agree that a simple optimization would be initializing the page cache at startup with some snapshot of the wiki. For this to work, you would of course need to have some updating mechanism in place that fetches page updates. Good that such a mechanism is already present ;).

    I agree that this feature is a simple optimization that would improve the UX initially immensely.
2.  You are getting a list menu upon clicking on a list where you are able to start a new list and remove or reorder an already present one. I am definitely not yet happy with this solution as it is non-obvious and non-standard. A better approach would probably be to have an "add list" button of some sort at the bottom of the lists and a "delete list" button in the top right corner or something. I did not yet put much effort into finding a new solution, but it should not be too hard to change things around and experiment.

    As for the lack of validation, this is pretty much on purpose. The application is meant to be "resilient to neglect", aka it should require as few updates in the future as possible so that it may remain functional even after it is not being actively supported anymore. Since the game is quite fresh, I expect list-building rules to be in flux for some time (the more recent example is champion models). So rather than serving non-up-to-date rules, I decided to not restrict anything. Of course, there could be different "modes", aka "free mode" without rules, and a "Warcaster mode" with those enforced rules or something. Of course, it would be more effort to implement.

3. I like the idea of (just) using a loading indicator. I am not very happy with the current loading solution anyway. Having a single loading bar would indeed be much better.

    The unit info is a complete mess at the moment. I am just putting everything in there at the moment with the goal to clean it up once everything that I need is there. E.g. I would still like to add links to PP's shop at the top of each card, but did not spend the time yet to parse them from the wiki pages (but this should not be too hard).

4.  Yeah a kind of guide like that would definitely be possible. It is low on my list of priorities at the moment, though, but I feel like it shouldn't be too hard to build.

Thanks for the kind words man! I have been spending some time on and off in the app, basically just because I enjoyed the idea. But it is getting to a point where I also think it should be put out there ;).

I would be happy for code contributions, to be honest. I used to have a lot of time to spend on projects like these, but these days I don't have so much time anymore. So a helping hand would be very welcome. I am not sure, however, how contributions could be coordinated. I feel like more solid project planning and an open (rough) roadmap or at least a list of open issues would be needed in this case. Bu maybe you have ideas on that as well?

**Comment by kirkbushell** [comment] 2022-10-09 11:00
Cheers!

In regards to the very last point, yeah I think we could document the issues (I can start putting them on), and I'd start with the loading of data, and then improving UI/UX and going from there.

I'd be very happy to take on each of those, if you'd have me contribute - I can then create PRs that address the issues and you can review from there :)

I do this on a pretty regular basis on numerous games, including Flesh & Blood, Moonstone, Rivenstone, and I was about to start a warcaster app until I found yours. I tend to move quite quickly on these things once I get momentum, most only take me a few weeks to get going.

**Comment by Yord** [comment] 2023-08-03 20:35
Let me summarize what happened for the points raised in this issue and close it:

1. The startup is intended as is and is unchanged. I may deliver pre-cached data in the future, but this is low on the priority list.
2. The UX has been completely revamped and should now (hopefully) be much better than it was when this issue was raised. The missing validation is by design and I have no plans on working on list validation.
3. Loading has been redesigned to only have a single loading screen as suggested in this issue. Unit info has gotten some dearly needed design work.
4. UI/UX has been redesigned with the intention to make it more approachable.

**Closed as completed by Yord** 2023-08-03 20:35 UTC
